project_id = "cdidlnlytaomnpoirwuz"

[functions.market-news]
verify_jwt = false

[functions.dashboard-news]
verify_jwt = false

[functions.google-search-console]
verify_jwt = false

[functions.ai-suggest-tasks]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.wrike-proxy]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false