// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';

const isMissingConfig = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
if (isMissingConfig) {
  console.error('[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY — check your .env file or Vercel environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Custom in-memory lock for the Supabase auth client.
 *
 * We can't use the default `navigatorLock` (Web Locks API) because it can
 * hang during `_initSupabaseAuthClient` and then abort with
 * "AbortError: signal is aborted without reason", blocking auth init and
 * leaving /home blank (seen when a proxy stalls the initial token refresh
 * inside the locked section, or when another tab holds the lock).
 *
 * We can't use the SDK's built-in `processLock` either, because it logs a
 * noisy `console.warn("Lock ... acquisition timed out after 0ms")` every
 * time the SDK's `_autoRefreshTokenTick` calls `_acquireLock(0, ...)` while
 * initial `initialize()` is still running — even though the SDK catches
 * the thrown `isAcquireTimeout` error and skips the tick gracefully.
 *
 * This implementation mirrors `processLock` but handles `acquireTimeout===0`
 * as a silent non-blocking check (like `navigatorLock`'s `ifAvailable: true`
 * branch) and preserves the previous continuation on failed acquire so the
 * chain stays intact.
 */
const LOCK_CONTINUATIONS: Record<string, Promise<unknown>> = {};

async function silentInMemoryLock<R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> {
  const key = `lock:${name}`;
  const previous = LOCK_CONTINUATIONS[key] ?? Promise.resolve();

  const wait = (async () => {
    if (acquireTimeout < 0) {
      // Wait forever.
      await previous.catch(() => null);
    } else if (acquireTimeout === 0) {
      // Non-blocking: succeed only if the previous operation has already
      // settled (flushed via a microtask). No warning is logged.
      let settled = false;
      previous.then(
        () => {
          settled = true;
        },
        () => {
          settled = true;
        },
      );
      await Promise.resolve();
      if (!settled) {
        throw Object.assign(
          new Error(`Lock ${name} not immediately available`),
          { isAcquireTimeout: true as const },
        );
      }
    } else {
      // Wait with timeout.
      await Promise.race([
        previous.catch(() => null),
        new Promise<never>((_, reject) => {
          setTimeout(() => {
            reject(
              Object.assign(
                new Error(
                  `Lock ${name} acquisition timed out after ${acquireTimeout}ms`,
                ),
                { isAcquireTimeout: true as const },
              ),
            );
          }, acquireTimeout);
        }),
      ]);
    }
  })();

  const operation = wait.then(() => fn());

  // Register this operation for subsequent callers. On a failed non-blocking
  // acquire, fall back to the previous continuation so we don't break the
  // chain for later waiters.
  LOCK_CONTINUATIONS[key] = operation.catch((e) => {
    if (e && (e as { isAcquireTimeout?: boolean }).isAcquireTimeout) {
      return previous;
    }
    return null;
  });

  return await operation;
}

const FALLBACK_URL = 'https://placeholder.supabase.co';
const FALLBACK_KEY = 'placeholder';

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: !isMissingConfig,
      autoRefreshToken: !isMissingConfig,
      lock: silentInMemoryLock,
    },
  },
);