// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Use an in-memory lock instead of the default Web Locks API.
    // `navigatorLock` can hang indefinitely (then abort with
    // "AbortError: signal is aborted without reason") when another tab
    // holds the lock or when a proxy stalls the initial token refresh,
    // which blocks `_initSupabaseAuthClient` and leaves /home blank.
    // `processLock` is in-memory and works fine for a single-tab app.
    lock: processLock,
  },
});